version: "3.9"

services:
  pfdb:
    image: bianjp/mariadb-alpine:latest
    environment:
      MYSQL_ROOT_PASSWORD: "banana"
    networks:
      pf:
        aliases:
          - "mariadb"
    volumes:
      - db_data:/var/lib/mysql
      - ./pathfinder/export/sql/eve_universe.sql.zip:/eve_universe.sql.zip
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  pf-redis:
    image: redis:6.2.5-alpine3.14
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      pf:
        aliases:
          - "redis"
    logging:
      driver: none
  pf-socket:
    image: ghcr.io/goryn-clade/pf-websocket:latest
    command: ["--tcpHost", "0.0.0.0"]
    networks:
      pf:
         aliases:
           - "pathfinder-socket"
    volumes:
      - ./logs:/var/www/html/pathfinder/history/map
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  pf:
    image: ghcr.io/goryn-clade/pathfinder:latest
    env_file:
      - .env

    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "incursions"
        traefik.http.services.pf.loadbalancer.server.port: 80
        traefik.http.routers.pf.rule: "Host(`pathfinder.latebroadcast.rip`)"
        traefik.http.routers.pf.entrypoints: "web"
        traefik.http.routers.pf-secure.rule: "Host(`pathfinder.latebroadcast.rip`)"
        traefik.http.routers.pf-secure.entrypoints: "websecure"
        traefik.http.routers.pf-secure.tls: "true"
          # traefik.http.routers.pf-secure.tls.certresolver: "letsencrypt"
        traefik.http.middlewares.redirecthttps.redirectscheme.scheme: "https"
        traefik.http.routers.pf.middlewares: "redirecthttps"
    networks:
      - pf
      - incursions
    healthcheck:
      disable: true
    volumes:
      - ./config/pathfinder/config.ini:/var/www/html/pathfinder/app/templateConfig.ini
      - ./config/pathfinder/pathfinder.ini:/var/www/html/pathfinder/app/pathfinder.ini
      - ./config/pathfinder/plugin.ini:/var/www/html/pathfinder/app/plugin.ini
      - ./logs:/var/www/html/pathfinder/history/map
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pfdb
      - pf-redis
      - pf-socket
    restart: always

volumes:
     db_data:
     redis_data:
networks:
    pf:
    incursions:
      external: true
