services:
  pfdb:
    image: bianjp/mariadb-alpine:latest
    environment:
      MYSQL_ROOT_PASSWORD: "banana"
    networks:
      pf:
        aliases:
          - "mariadb"

    # configs: TODO: Fix so it adds appropriately
    #   - source: pathfinder_universe.1
    #     target: /eve_universe.sql.zip
    #     mode: 0444
    volumes:
      - db_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  pf-redis:
    image: redis:6.2.5-alpine3.14
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      pf:
        aliases:
          - "redis"
  pf-socket:
    image: ghcr.io/goryn-clade/pf-websocket:latest
    command: ["--tcpHost", "0.0.0.0"]
    networks:
      pf:
         aliases:
           - "pathfinder-socket"
    volumes:
      - pf_logs:/var/www/html/pathfinder/history/map
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  pf:
    image: ghcr.io/goryn-clade/pathfinder:latest
    env_file:
      - .env

    deploy:
      labels:
        traefik.enable: "true"
        traefik.docker.network: "incursions"
        traefik.http.services.pf.loadbalancer.server.port: 80
        traefik.http.routers.pf.rule: "Host(`pathfinder.latebroadcast.rip`)"
        traefik.http.routers.pf.entrypoints: "web"
        traefik.http.routers.pf-secure.rule: "Host(`pathfinder.latebroadcast.rip`)"
        traefik.http.routers.pf-secure.entrypoints: "websecure"
        traefik.http.routers.pf-secure.tls: "true"
          # traefik.http.routers.pf-secure.tls.certresolver: "letsencrypt"
        traefik.http.middlewares.redirecthttps.redirectscheme.scheme: "https"
        traefik.http.routers.pf.middlewares: "redirecthttps"
    networks:
      - pf
      - incursions
    healthcheck:
      disable: true # FIXME
    volumes:
      - pf_logs:/var/www/html/pathfinder/history/map
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    configs:
      - source: pathfinder_main_config.1
        target: /var/www/html/pathfinder/app/templateConfig.ini
        mode: 0444
      - source: pathfinder_ini.1
        target: /var/www/html/pathfinder/app/pathfinder.ini
        mode: 0444
      - source: pathfinder_plugin_config.1
        target: /var/www/html/pathfinder/app/plugin.ini
        mode: 0444
    depends_on:
      - pfdb
      - pf-redis
      - pf-socket
    restart: always

configs:
  pathfinder_main_config.1:
    file: ./config/pathfinder/config.ini
  pathfinder_ini.1:
    file: ./config/pathfinder/pathfinder.ini
  pathfinder_plugin_config.1:
    file: ./config/pathfinder/plugin.ini



volumes:
     pf_logs:
     db_data:
     redis_data:


networks:
    pf:
    incursions:
      external: true
